import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
import {NAV,PREF_KEY,readPreferences} from '../src/experience.js';
const bundle=await build({entryPoints:['src/app.js'],bundle:true,format:'iife',write:false});
async function mount(storage={}){const dom=new JSDOM(await readFile('public/design-studio/index.html','utf8'),{url:'https://visionweaver.example',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async()=>({ok:true,json:async()=>({cloudConfigured:false})});for(const [k,v]of Object.entries(storage))w.localStorage.setItem(k,v);w.eval(bundle.outputFiles[0].text);await new Promise(r=>setTimeout(r,10));return dom;}
test('approved navigation opens every workspace without replacing existing avatar and scene editors',async()=>{const d=await mount();try{const {document}=d.window;assert.equal(document.querySelector('h1').textContent,'Bring your ideas to life.');for(const [id]of NAV){document.querySelector(`nav [data-page="${id}"]`).click();assert.equal(d.window.location.hash,'#'+id);assert.ok(document.querySelector('main h1'));}document.querySelector('nav [data-page="avatars"]').click();assert.ok(document.querySelector('#character-form'));document.querySelector('nav [data-page="scenes"]').click();assert.ok(document.querySelector('#scene-form'));assert.equal(document.querySelector('header [aria-label="Account and cloud"]'),null);assert.equal(document.querySelectorAll('.account-control').length,1);assert.ok(document.querySelector('.thelma-block'));}finally{d.window.close();}});
test('view, theme and collapsed navigation survive a fresh page load',async()=>{const d=await mount();let pref;try{const doc=d.window.document;doc.querySelector('nav [data-page="settings"]').click();doc.querySelector('[data-id="studio:3"]').click();doc.querySelector('[data-id="light"]').click();doc.querySelector('[data-act="nav-toggle"]').click();pref=d.window.localStorage.getItem(PREF_KEY);doc.querySelector('nav [data-page="studio"]').click();assert.equal(doc.documentElement.dataset.view,'3');assert.equal(doc.documentElement.dataset.scheme,'light');assert.equal(doc.documentElement.dataset.navCollapsed,'true');}finally{d.window.close();}const reload=await mount({[PREF_KEY]:pref});try{reload.window.document.querySelector('nav [data-page="studio"]').click();assert.equal(reload.window.document.documentElement.dataset.view,'3');assert.equal(reload.window.document.documentElement.dataset.scheme,'light');}finally{reload.window.close();}});
test('a location pack saves and reloads with its source and next action',async()=>{const d=await mount();let saved;try{const doc=d.window.document;doc.querySelector('nav [data-page="worlds"]').click();doc.querySelector('[data-act="plan-new"]').click();doc.querySelector('#title').value='Chicago location pack';doc.querySelector('#notes').value='Pigeons downtown; record light direction before the next scene.';doc.querySelector('#source').value='https://example.com/source';doc.querySelector('#dialog-form').dispatchEvent(new d.window.Event('submit',{bubbles:true,cancelable:true}));assert.ok(doc.querySelector('main').textContent.includes('Chicago location pack'));saved=d.window.localStorage.getItem('visionweaver-production-records-v1');}finally{d.window.close();}const reload=await mount({'visionweaver-production-records-v1':saved});try{reload.window.document.querySelector('nav [data-page="worlds"]').click();assert.ok(reload.window.document.querySelector('main').textContent.includes('Pigeons downtown'));}finally{reload.window.close();}});
test('retired or invalid visual preferences fall back to approved values',()=>{const pref=readPreferences({getItem:()=>JSON.stringify({scheme:'notebook',views:{studio:99,worlds:2},collapsed:true})});assert.equal(pref.scheme,'neon');assert.equal(pref.views.studio,undefined);assert.equal(pref.views.worlds,2);});
test('global search finds saved avatar and scene names and opens the selected editor',async()=>{const d=await mount();try{const doc=d.window.document;doc.querySelector('[data-act="command"]').click();const search=doc.querySelector('#command-search');search.value='Chicago';search.dispatchEvent(new d.window.Event('input',{bubbles:true}));const avatar=doc.querySelector('[data-command-character]');assert.equal(avatar.hidden,false);avatar.click();assert.equal(d.window.location.hash,'#avatars');assert.ok(doc.querySelector('#character-form'));doc.querySelector('[data-act="command"]').click();doc.querySelector('[data-command-scene]').click();assert.ok(doc.querySelector('#scene-form'));}finally{d.window.close();}});
test('all approved references have distinct archived paths and readable files',async()=>{const assets=JSON.parse(await readFile('docs/APPROVED_UI_ASSETS.json','utf8'));assert.equal(assets.length,26);assert.equal(new Set(assets.map(a=>a.file)).size,26);for(const asset of assets)assert.ok((await readFile('public/'+asset.file)).length>0);});
