import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {createApp} from '../server/index.mjs';
import {triage,productionGate} from '../server/policy.mjs';
import {sampleCharacter,validateCharacter,validateScene,safeProductUrl,draftExport} from '../src/model.js';
const uid='ad510000-0000-4000-8000-000000000001';
async function fixture(t,env={},fetcher=fetch){const server=http.createServer(createApp(env,fetcher));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}`;}
test('unconfigured deployment never accepts cloud or production requests',async t=>{const url=await fixture(t);for(const path of ['/api/workspaces','/api/render','/mcp']){const r=await fetch(url+path,{method:'POST',body:'{}'});assert.equal(r.status,503);}const cfg=await (await fetch(url+'/api/config')).json();assert.equal(cfg.cloudConfigured,false);assert.equal(cfg.production.allowed,false);});
test('configured API rejects missing tokens and cross-origin calls',async t=>{const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',APP_ORIGIN:'https://studio.example'});assert.equal((await fetch(url+'/api/workspaces')).status,401);assert.equal((await fetch(url+'/api/config',{headers:{Origin:'https://attacker.example'}})).status,403);});
test('token identity is verified; database gets user token, never a service credential',async t=>{const calls=[];const mock=async(url,opts)=>{calls.push([url,opts]);return new Response(JSON.stringify(url.endsWith('/user')?{id:uid,is_anonymous:false}:[]),{status:200});};const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'},mock);const r=await fetch(url+'/api/workspaces',{headers:{Authorization:'Bearer verified.token'}});assert.equal(r.status,200);assert.equal(calls[0][0],'https://example.supabase.co/auth/v1/user');assert.equal(calls[1][1].headers.Authorization,'Bearer verified.token');});
test('anonymous identities and expired tokens cannot access records',async t=>{for(const response of [{id:uid,is_anonymous:true},null]){const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'},async()=>new Response(JSON.stringify(response),{status:response?200:401}));assert.ok([401,403].includes((await fetch(url+'/api/workspaces',{headers:{Authorization:'Bearer token'}})).status));}});
test('render and public commerce remain blocked even for authenticated accounts',async t=>{const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'},async()=>new Response(JSON.stringify({id:uid})));for(const path of ['/api/render','/api/uploads','/api/publish','/api/checkout','/api/store/listings'])assert.equal((await fetch(url+path,{method:'POST',headers:{Authorization:'Bearer token'},body:'{}'})).status,423);});
test('MCP cannot execute unlisted tools or generation',async t=>{const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'},async()=>new Response(JSON.stringify({id:uid})));const r=await fetch(url+'/mcp',{method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'render'}})});assert.equal((await r.json()).error.code,-32602);});
test('forged approval fields are not forwarded when saving',async t=>{let stored;const url=await fixture(t,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'},async(url,opts)=>{if(url.endsWith('/user'))return new Response(JSON.stringify({id:uid}));stored=JSON.parse(opts.body);return new Response('[]');});const r=await fetch(url+'/api/versions',{method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({workspace_id:uid,kind:'project',name:'Draft',document:{},review_state:'approved',author_id:'someone-else'})});assert.equal(r.status,201);assert.equal(stored.author_id,uid);assert.equal(stored.review_state,undefined);});
test('prohibited metadata is blocked; unknown text is never cleared for production',()=>{assert.equal(triage('nude child').decision,'BLOCK');assert.equal(triage('kids performing illegal acts').decision,'BLOCK');assert.equal(triage('adult graphic scene').decision,'REVIEW');assert.equal(triage('community room').decision,'DRAFT_ONLY');assert.equal(productionGate().allowed,false);});
test('character input rejects invalid ages and unsafe product schemes',()=>{assert.throws(()=>validateCharacter({...sampleCharacter,age:-1}));assert.throws(()=>validateCharacter({...sampleCharacter,productUrl:'javascript:alert(1)'}));assert.equal(safeProductUrl('https://u:p@example.com'),null);assert.equal(validateCharacter({...sampleCharacter,status:'Approved',coverage:64}).status,'Draft');assert.equal(validateCharacter({...sampleCharacter,coverage:64}).coverage,0);});
test('scene timing cannot put contact outside its event interval',()=>{assert.throws(()=>validateScene({name:'test',characterId:sampleCharacter.id,space:'Community Room',x:50,y:50,duration:6,contact:9},[sampleCharacter]));assert.equal(draftExport([],{}).status,'DRAFT_NOT_PRODUCTION');});
