import {createClient} from '@supabase/supabase-js';
import {TITLE,VERSION,BOARDS,sampleCharacter,newScene,validateCharacter,validateScene,draftExport,safeProductUrl} from './model.js';
const $=s=>document.querySelector(s);
const asset=p=>window.__DS_ASSETS__?.[p]||'./'+p;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='visionweaver-design-studio-v1';
let state;try{state=JSON.parse(localStorage.getItem(key));if(!Array.isArray(state?.characters)||!state?.scene)state=null;}catch{}
state ||= {characters:[structuredClone(sampleCharacter)],scene:newScene(),history:[]};
let page='studio',config={},client=null,session=null,workspace='',workspaces=[],connections=[],cloudVersions=[],timer;
let selected=state.characters[0]?.id||'chicago-character';
const pages=[['studio','Studio'],['avatars','Avatars'],['scenes','Scenes'],['performances','Performances'],['effects','Effects'],['store','Store'],['licenses','My Licenses'],['connections','Connections'],['designs','Design History']];
function notify(message){$('#notice').textContent=message;$('#notice').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#notice').style.display='none',7000);}
function current(){return state.characters.find(c=>c.id===selected)||state.characters[0];}
function saveLocal(){localStorage.setItem(key,JSON.stringify(state));}
function field(label,name,value,type='text'){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" max="150" step="1"':''}></div>`;}
function guide(title,text){return `<div class="guide"><strong>${title}</strong><p>${text}</p></div>`;}
function steps(items){return `<div class="steps">${items.map((s,i)=>`<span>${i+1}&nbsp; ${s}</span>`).join('')}</div>`;}
function boardPanel(){return `<h2>Your Three Boards</h2>${BOARDS.map((b,i)=>`<div class="row"><strong>${b}</strong><span>${i===0?'Draft':i===1?'Not Created':'Draft Scene'}</span></div>`)}${guide('Reference coverage','0 approved views. A 32-view master and calibrated 64-view expansion require asset creation and review. A diagram is not a character reference.')}`;}
function render(){
 $('#app').innerHTML=`<header><div class="brand">VisionWeaver <span>| Design Studio</span></div><div class="actions"><span class="badge">BUILD ${VERSION} · DRAFT WORKSPACE</span><button id="account">${session?'Account and Cloud':'Sign In / Cloud Setup'}</button></div></header><div class="shell"><nav aria-label="Design navigation">${pages.map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}" aria-current="${page===id?'page':'false'}">${label}</button>`).join('')}</nav><main>${views[page]()}</main></div>`;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});
 $('#account').onclick=()=>{page='licenses';render();};
 document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>run(b.dataset.act,b.dataset.id));
 $('#character-form')?.addEventListener('submit',e=>{e.preventDefault();const old=current();try{const c=validateCharacter({...old,...Object.fromEntries(new FormData(e.target))});c.revision=(old.revision||0)+1;state.characters[state.characters.findIndex(v=>v.id===old.id)]=c;checkpoint('character',c);notify('Character draft saved on this device.');render();}catch(e){notify(e.message);}});
 $('#scene-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);try{state.scene=validateScene({...state.scene,...Object.fromEntries(f),duration:Number(f.get('duration')),contact:Number(f.get('contact')),x:Number(f.get('x')),y:Number(f.get('y')),light:f.has('light'),roomTone:f.has('roomTone'),streetSound:f.has('streetSound')},state.characters);state.scene.revision++;checkpoint('scene',state.scene);notify('Scene draft saved.');render();}catch(e){notify(e.message);}});
 $('#workspace')?.addEventListener('change',e=>{workspace=e.target.value;});
 $('#catalog-search')?.addEventListener('input',e=>{for(const card of document.querySelectorAll('[data-character]'))card.hidden=!card.dataset.character.toLowerCase().includes(e.target.value.toLowerCase());});
}
function checkpoint(kind,document){state.history.unshift({id:crypto.randomUUID(),kind,at:new Date().toISOString(),document:structuredClone(document)});state.history=state.history.slice(0,100);saveLocal();}
function planSVG(){const s=state.scene;const c=state.characters.find(c=>c.id===s.characterId);return `<svg viewBox="0 0 700 390" role="img" aria-label="Editable overhead blocking diagram, not a rendered image"><rect x="35" y="38" width="630" height="310" rx="12" fill="${s.space==='Open Plaza'?'#293f3d':'#283344'}" stroke="#9aabbe" stroke-width="3"/><path d="M60 110H640M60 170H640M60 230H640M60 290H640M160 60V325M280 60V325M400 60V325M520 60V325" stroke="#445367"/>${s.space==='Community Room'?'<rect x="290" y="40" width="140" height="12" fill="#cdd7e6"/><text x="310" y="82" fill="#cdd7e6" font-size="16">Screen</text><rect x="450" y="170" width="110" height="65" fill="#8e705a"/><text x="470" y="208" fill="white" font-size="16">Table</text>':'<circle cx="480" cy="170" r="52" fill="#385f52"/><text x="449" y="175" fill="white" font-size="16">Planter</text>'}<g id="avatar-marker" transform="translate(${60+s.x*5.7},${70+s.y*2.5})"><circle r="26" fill="#843ff0" stroke="#dac9ff" stroke-width="3"/><text y="5" text-anchor="middle" fill="white" font-size="12">Avatar</text></g><path d="M110 300L225 220L230 325Z" fill="#268ada33" stroke="#5fa5d9"/><text x="75" y="337" fill="#bedaff" font-size="16">Camera 1</text><text x="350" y="378" text-anchor="middle" fill="#c7cfe3" font-size="15">${esc(c?.name||'Select a character')}</text></svg>`;}
const views={
 studio:()=>`<div class="bar"><div><h1>Your Scene, Connected</h1><p class="lead">Characters, space, motion, and sound in one workspace.</p></div><button data-act="export">Export Draft</button></div>${steps(['Assemble','Direct','Review','Export'])}<div class="workspace"><section class="panel"><h2>Build Your World</h2>${state.characters.map(c=>`<div class="card"><span class="badge">Draft</span><h3>${esc(c.name)}</h3><p>${esc(c.clothing)}</p><button data-act="load" data-id="${esc(c.id)}">Load Character</button></div>`).join('')}<div class="actions"><button data-page="avatars">Create Avatar</button><button data-page="scenes">Edit Scene</button></div></section><section><div class="stage"><span class="stage-label">OVERHEAD BLOCKING · DRAFT</span>${planSVG()}<div class="stage-caption">${esc(state.scene.space)} · Editable staging diagram. Rendered preview is not available.</div></div><div class="panel timeline"><h2>Action and Reaction</h2><p class="hint">${state.scene.duration} seconds · Contact at ${state.scene.contact} seconds</p><div class="track">Character <div class="clip">${esc(state.scene.action)}</div></div><div class="track">Object <div class="clip orange">${esc(state.scene.reaction)}</div></div><div class="track">Camera <div class="clip blue">${esc(state.scene.camera)}</div></div><div class="track">Sound <div class="clip green">${state.scene.roomTone?'Room Tone':'Muted'}</div></div><button data-act="preview">Play Timing Preview</button><p id="playback" class="hint" aria-live="polite">Ready to rehearse the event timing.</p></div></section><aside class="panel"><h2>Scene Controls</h2><div class="row">Appearance <span>Draft</span></div><div class="row">Reference Views <span>Not Created</span></div><div class="row">Afternoon Light <span>${state.scene.light?'On':'Off'}</span></div><div class="row">Street Sound <span>${state.scene.streetSound?'On':'Off'}</span></div>${guide('Next Step','Open Avatars to enter the details, then Scenes to set placement and timing.')}<div class="actions"><button data-page="designs">View Design Mockups</button></div></aside></div>`,
 avatars:()=>`<div class="bar"><div><h1>Avatar Catalog</h1><p class="lead">Define the person. Review the look. Control the use.</p></div><button class="primary" data-act="new">Create Avatar</button></div><input id="catalog-search" aria-label="Search your catalog" placeholder="Search your catalog"><div class="cards">${state.characters.map(c=>`<article class="card" data-character="${esc(c.name)}"><span class="badge">Draft</span><h2>${esc(c.name)}</h2><p>${esc(c.representation)} · Age ${esc(c.age)}<br>${esc(c.origin)} · ${esc(c.height)} · ${esc(c.weight)}</p><button data-act="edit" data-id="${esc(c.id)}">Edit Character</button></article>`).join('')}</div>${steps(['Enter Details','Review Appearance','Build References','Set Permissions'])}<div class="workspace"><form id="character-form" class="panel"><h2>Character Details</h2>${[['Name','name'],['Representation','representation'],['Age','age'],['Origin','origin'],['Height','height'],['Weight','weight'],['Hair and Beard','hair'],['Glasses','glasses'],['Clothing','clothing'],['Voice and Accent','voice'],['Product Link','productUrl']].map(([l,n])=>field(l,n,current()?.[n],n==='age'?'number':'text')).join('')}<button class="primary" type="submit">Save Character Draft</button></form><section class="panel"><h2>Appearance Preview</h2><img class="reference" src="${asset('mockups/v2-character-workspace.png')}" alt="Preserved Version 2 character workspace design reference"><p class="hint">Design reference only. Editing this form does not regenerate the pictured character.</p>${guide('First-Time Guide','Save a draft here. Reference image generation and review must be connected before this character can be approved for production.')}<h3>Linked Products</h3><p>Product Match Pending</p>${safeProductUrl(current()?.productUrl)?`<a href="${esc(safeProductUrl(current().productUrl))}" target="_blank" rel="noopener noreferrer">Open Supplied Product Link</a>`:''}<h3>Usage and Licensing</h3><p>Private draft. Store listing not published. No commercial license is granted.</p></section><aside class="panel">${boardPanel()}<h3>Appearance History</h3>${state.history.filter(h=>h.kind==='character'&&h.document.id===current()?.id).slice(0,8).map(h=>`<div class="row">Version ${esc(h.document.revision)}<button data-act="restore" data-id="${h.id}">Restore as Draft</button></div>`).join('')||'<p>No saved versions yet.</p>'}</aside></div>`,
 scenes:()=>`<h1>Scene Builder</h1><p class="lead">Plan the space, placement, and event timing.</p><div class="split"><form id="scene-form" class="panel">${field('Scene Name','name',state.scene.name)}<div class="field"><label for="space">Space</label><select name="space" id="space">${['Community Room','Open Plaza'].map(v=>`<option ${v===state.scene.space?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="characterId">Character</label><select name="characterId" id="characterId">${state.characters.map(c=>`<option value="${esc(c.id)}" ${c.id===state.scene.characterId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>${field('Action','action',state.scene.action)}${field('Reaction','reaction',state.scene.reaction)}${field('Camera Direction','camera',state.scene.camera)}${['x','y'].map(n=>`<div class="field"><label for="${n}">Position ${n.toUpperCase()} (0 to 100)</label><input id="${n}" name="${n}" type="range" min="0" max="100" value="${state.scene[n]}"></div>`).join('')}<div class="field"><label for="duration">Duration in Seconds</label><input name="duration" id="duration" type="number" min="1" max="60" value="${state.scene.duration}"></div><div class="field"><label for="contact">Contact Time in Seconds</label><input name="contact" id="contact" type="number" step="0.1" min="0" max="60" value="${state.scene.contact}"></div>${[['light','Afternoon Light'],['roomTone','Room Tone'],['streetSound','Street Sound']].map(([n,l])=>`<label class="row">${l}<input name="${n}" type="checkbox" ${state.scene[n]?'checked':''}></label>`).join('')}<div class="actions"><button class="primary">Save Scene Draft</button></div></form><section><div class="stage">${planSVG()}</div>${guide('Location Necessities','This is an authored generic room or plaza. A real city, era, landmark, weather pattern, and cultural setting require a sourced world-anchor record.')}<p>Audio controls save intent; they do not play licensed sound or simulate acoustics.</p></section></div>`,
 performances:()=>`<h1>Performance Library</h1><p class="lead">Author actions now. Tested movement packages come next.</p><div class="cards">${['Wave','Reach','Walk','Present'].map(a=>`<section class="card"><h2>${a}</h2><p>Timing label for a draft scene. No rig or motion file is included.</p><button data-act="action" data-id="${a}">Use in Draft</button></section>`).join('')}</div>${guide('Compatibility','Performance packages must declare supported rigs, body plans, contact points, space requirements, voice rights, and permitted uses.')}`,
 effects:()=>`<h1>Effects Lab</h1><p class="lead">Time, perception, camera, and sound must remain connected.</p><div class="cards">${['Time Stretch','Orbit Freeze','Selective Time'].map(t=>`<section class="card"><h2>${t}</h2><span class="badge">Specification Only</span><p>Requires a tested rendering adapter, per-subject timing, collision rules, and sound treatment.</p></section>`).join('')}</div>${guide('Design origin','Inspired by loading spaces and the Analyst’s time manipulation in the Matrix films. No copyrighted film assets or character likenesses are included.')}`,
 store:()=>`<h1>Design Store</h1><p class="lead">A future marketplace for approved characters, environments, and performances.</p><div class="panel empty"><h2>No Published Listings</h2><p>Checkout and seller publication are disabled. Drafts are private. No prices, licenses, or sales have been invented.</p></div><div class="cards">${['Character Packages','Appearance Expansions','Environments','Performance Packages'].map(t=>`<section class="card"><h2>${t}</h2><p>Planned category. Listings must declare exact files, permissions, compatibility, provenance, and support.</p></section>`).join('')}</div>`,
 licenses:()=>`<h1>Account, Cloud, and Licenses</h1><p class="lead">Local drafts work without an account. Cloud saving requires verified sign-in.</p><div class="split"><section class="panel"><h2>${session?'Signed In':'Sign In'}</h2><p>${session?esc(session.user.email||session.user.id):config.cloudConfigured?'Choose an enabled identity provider.':'Cloud authentication is not configured for this deployment.'}</p><div class="actions">${session?'<button data-act="signout">Sign Out</button>':(config.oauthProviders||[]).map(p=>`<button data-act="signin" data-id="${p}">Continue with ${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</div><h3>Cloud Workspace</h3><select id="workspace" aria-label="Cloud workspace"><option value="">Select a workspace</option>${workspaces.map(w=>`<option value="${w.id}" ${w.id===workspace?'selected':''}>${esc(w.name)}</option>`).join('')}</select><div class="actions"><button data-act="create-workspace" ${!session?'disabled':''}>Create Workspace</button><button data-act="cloud-save" ${!session?'disabled':''}>Save Project to Cloud</button><button data-act="cloud-load" ${!session?'disabled':''}>List Cloud Drafts</button></div>${cloudVersions.map(v=>`<div class="row"><span>${esc(v.name)}<br>${esc(v.created_at)}</span><button data-act="cloud-restore" data-id="${v.id}">Load Draft</button></div>`).join('')}</section><section class="panel"><h2>Licenses</h2><p>No purchased licenses. Adult-content policy and seller terms are pending legal review.</p><h3>Safety by Default</h3><p>Child nudity, child sexualization, exploitation, nonconsensual intimate imagery, and fraudulent impersonation are prohibited. Restricted requests require review. Generation, uploads, and publication are disabled in this release.</p><h3>Data Handling</h3><p>Local drafts stay in this browser. Cloud drafts use tenant access checks. Tokens remain in session storage; sign out when finished. Do not enter sensitive personal information into a demo.</p></section></div>`,
 connections:()=>`<h1>Connections</h1><p class="lead">API and MCP access must be authorized and tested for each account.</p><div class="panel"><p>Read-only MCP endpoint: <code>/mcp</code>. Requires a valid user bearer token. Automatic OAuth discovery and provider execution are not yet enabled.</p><table class="table"><thead><tr><th>Provider</th><th>Intended Use</th><th>Status</th></tr></thead><tbody>${connections.map(c=>`<tr><td><a href="${esc(c.docs)}" rel="noopener noreferrer" target="_blank">${esc(c.name)}</a></td><td>${esc(c.capability)}</td><td>${esc(c.status)}</td></tr>`).join('')}</tbody></table></div>`,
 designs:()=>`<h1>Design History</h1><p class="lead">Original mockups preserved unchanged. These are design references, not screenshots of shipped rendering features.</p>${[['v1-avatar-catalog','Version 1: Avatar Catalog'],['v1-scene-builder','Version 1: Scene Builder'],['v2-design-studio','Version 2: Design Studio'],['v2-character-workspace','Version 2: Character Workspace']].map(([f,t])=>`<section class="panel"><h2>${t}</h2><a href="${asset('mockups/'+f+'.png')}" target="_blank" rel="noopener"><img class="reference" src="${asset('mockups/'+f+'.png')}" alt="${t}" loading="lazy"></a></section>`).join('')}`
};
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.access_token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||data.message||'Request failed.');return data;}
async function run(action,id){try{
 if(action==='new'){const c={...sampleCharacter,id:crypto.randomUUID(),name:'New Character',representation:'',age:18,origin:'',height:'',weight:'',hair:'Not Set',glasses:'Not Set',clothing:'Not Set',productUrl:'',revision:0};state.characters.push(c);selected=c.id;saveLocal();render();}
 if(action==='edit'){selected=id;page='avatars';render();}
 if(action==='load'){state.scene.characterId=id;saveLocal();notify('Character loaded into the draft scene.');render();}
 if(action==='action'){state.scene.action=id;saveLocal();page='scenes';render();}
 if(action==='restore'){const old=state.history.find(h=>h.id===id);if(!old)return;const c={...structuredClone(old.document),revision:(current().revision||0)+1,status:'Draft'};state.characters[state.characters.findIndex(v=>v.id===c.id)]=c;checkpoint('character',c);render();notify('Restored as a new draft version.');}
 if(action==='export'){const blob=new Blob([JSON.stringify(draftExport(state.characters,state.scene),null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='visionweaver-design-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 if(action==='preview'){const start=performance.now();const scene=structuredClone(state.scene);const tick=()=>{const p=$('#playback');if(!p)return;const t=Math.min((performance.now()-start)/1000,scene.duration);p.textContent=`${t.toFixed(1)} s / ${scene.duration} s - ${t<scene.contact?scene.action:scene.reaction+' / Contact'}`;if(t<scene.duration)requestAnimationFrame(tick);};tick();}
 if(action==='signin'){if(!client)throw Error('Authentication is not configured.');const {error}=await client.auth.signInWithOAuth({provider:id,options:{redirectTo:location.origin+location.pathname}});if(error)throw error;}
 if(action==='signout'){await client.auth.signOut();session=null;workspaces=[];cloudVersions=[];workspace='';render();}
 if(action==='create-workspace'){const name=prompt('Workspace name');if(!name)return;const result=await api('/api/workspaces','POST',{name});workspace=result[0].id;workspaces=await api('/api/workspaces');render();}
 if(action==='cloud-save'){if(!workspace)throw Error('Select a cloud workspace first.');await api('/api/versions','POST',{workspace_id:workspace,kind:'project',name:state.scene.name,document:draftExport(state.characters,state.scene)});notify('A new private cloud draft version was saved.');}
 if(action==='cloud-load'){if(!workspace)throw Error('Select a cloud workspace first.');cloudVersions=await api('/api/versions?workspace='+encodeURIComponent(workspace));render();}
 if(action==='cloud-restore'){const v=cloudVersions.find(v=>v.id===id);const d=v?.document;if(d?.format!=='visionweaver.design-draft'||!Array.isArray(d.characters)||d.characters.length>100)throw Error('Unsupported draft format.');const chars=d.characters.map(validateCharacter);const scene=validateScene(d.scene,chars);state.characters=chars;state.scene=scene;selected=chars[0]?.id;checkpoint('project',d);page='studio';render();notify('Cloud draft loaded on this device.');}
 }catch(e){notify(e.message);}}
render();
try{if(window.__DS_EMBEDDED__)throw Error('Embedded local mode');config=await api('/api/config');connections=await api('/api/connectors');if(config.cloudConfigured){client=createClient(config.supabaseUrl,config.publishableKey,{auth:{flowType:'pkce',storage:sessionStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange((_event,s)=>{session=s;setTimeout(async()=>{try{workspaces=s?await api('/api/workspaces'):[];render();}catch(e){notify(e.message);}},0);});const {data}=await client.auth.getSession();session=data.session;if(session)workspaces=await api('/api/workspaces');}render();}catch{notify('Local draft mode. Cloud services are not available at this address.');}
