import {createClient} from '@supabase/supabase-js';
import {VERSION,TITLE,uid,newProject,newScene,makeCharacter,makeVariant,migrateProject,validateCharacter,validateScene,coverageCells,reviewProject,draftExport,importDraft,compileBrief,safeProductUrl,TRACKS} from './model.js';
import {connectors as registry} from '../server/connectors.mjs';
import {esc,icon,btn,tag,field,head,time} from './ui.js';
import {PAGES,pages} from './pages.js';
import {MOTIONS} from './catalog.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='visionweaver-design-studio-v1';
const asset=p=>window.__DS_ASSETS__?.[p]||'./'+p;
let originalRaw=null,loadError='',p;
try{originalRaw=localStorage.getItem(KEY);p=migrateProject(originalRaw?JSON.parse(originalRaw):null);}catch(e){p=newProject();loadError=e.message;}
const ui={page:PAGES.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'studio',characterId:p.characters[0].id,castId:'',avatarTab:'identity',sceneTab:'world',historyTab:'revisions',stage:'blocking',dirty:false};
const cloud={config:{},session:null,workspaces:[],workspace:'',versions:[],apiReady:false};
let client=null,connectors=registry,toastTimer,playFrame=0,playTime=0,undoStack=[],modalReturn=null;
const dirtyForms=new Set();
const scene=()=>p.scenes.find(s=>s.id===p.activeSceneId)||p.scenes[0];
const character=()=>p.characters.find(c=>c.id===ui.characterId)||p.characters[0];
const snapshot=project=>({...structuredClone(project),history:[]});
function notify(message,error=false){let el=$('#notice');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5500);}
function persist(next){if(loadError)throw Error('Recover or export the existing draft before starting a new project.');next.savedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('This browser could not save the change. Free storage or export your project. Your last saved draft is intact.');}}
function commit(kind,label,mutate,options={}){const before=snapshot(p),next=structuredClone(p);mutate(next);for(const c of next.characters)validateCharacter(c);for(const s of next.scenes)validateScene(s,next.characters);if(!options.quiet){next.history.unshift({id:uid(),kind,label,at:new Date().toISOString(),summary:options.summary||'Saved locally · draft authoring only',document:snapshot(next)});next.history=next.history.slice(0,30);}persist(next);undoStack.push(before);undoStack=undoStack.slice(-20);p=next;ui.dirty=false;}
function updateCharacter(values,label='Character details saved'){const id=character().id;commit('character',label,n=>{const i=n.characters.findIndex(c=>c.id===id);n.characters[i]=makeCharacter(validateCharacter({...n.characters[i],...values,revision:n.characters[i].revision+1}));});}
function updateScene(values,label='Scene direction saved'){const id=scene().id;commit('scene',label,n=>{const i=n.scenes.findIndex(s=>s.id===id);n.scenes[i]={...n.scenes[i],...values,revision:n.scenes[i].revision+1};});}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function stopPlayback(){cancelAnimationFrame(playFrame);playFrame=0;}
function render(){stopPlayback();const s=scene(),c=character();if(!s.cast.some(i=>i.id===ui.castId))ui.castId=s.cast[0]?.id||'';document.title=TITLE;document.documentElement.dataset.density=p.preferences.density;
 $('#app').innerHTML=`<a class="skip-link" href="#main">Skip to workspace</a><div class="app-shell"><aside class="sidebar"><a class="brand" href="#studio" aria-label="VisionWeaver Design Studio"><span class="brand-mark">${icon('effects',25)}</span><span>Vision<span class="brand-violet">Weaver</span><small>DESIGN STUDIO</small></span></a><button class="workspace-switch" data-page="tiers"><span class="workspace-avatar">EC</span><span>Estiban Creations<small>${esc(p.preferences.tier)} planning workspace</small></span>${icon('settings',15)}</button><nav aria-label="Design navigation">${PAGES.map(([id,label,group])=>`${group?`<span class="nav-group">${group}</span>`:''}<button data-page="${id}" class="nav-item ${ui.page===id?'active':''}" ${ui.page===id?'aria-current="page"':''}>${icon(id)}<span>${label}</span>${id==='review'?`<small>${reviewProject(p).length}</small>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><button class="nav-item" data-act="guide">${icon('help')}<span>Getting started</span></button><div class="build-label"><i class="dot"></i> ${VERSION} <span>Draft authoring</span></div></div></aside><div class="main-shell"><header class="topbar"><div class="breadcrumbs">Workspace <span>/</span> <strong>${PAGES.find(([id])=>id===ui.page)?.[1]}</strong></div><div class="top-actions"><span class="save-state" id="save-state">${icon('check',14)} ${p.savedAt?'Saved on this device':'New local draft'}</span><button class="command-button" data-act="command" aria-label="Search pages and actions">${icon('search',15)}<span>Quick find</span><kbd>⌘ K</kbd></button><button class="icon-btn" data-act="undo" aria-label="Undo last saved change" ${!undoStack.length?'disabled':''}>${icon('undo')}</button><button class="account-button" data-page="licenses" aria-label="Account and cloud">EC</button></div></header><main id="main" tabindex="-1">${loadError?`<div class="note error"><strong>Existing draft needs recovery: ${esc(loadError)}</strong>${btn('Download original','recover-export')}${btn('Start fresh after backup','recover-new')}</div>`:''}${pages({p,s,c,ui,cloud,connectors,asset})[ui.page]()}<footer class="page-footer"><span>VisionWeaver | Design Studio</span><span>Private draft authoring · ${VERSION}</span></footer></main></div></div>`;
 bindForms();bindFilters();bindStage();bindScrubber();
}
function saveVisible(){if(!ui.dirty)return true;const forms=$$('main form').filter(f=>dirtyForms.has(f.id));if(forms.some(f=>!f.reportValidity()))return false;try{for(const f of forms)saveForm(f);dirtyForms.clear();ui.dirty=false;return true;}catch(e){ui.dirty=true;notify(e.message,true);return false;}}
function navigate(page){if(!PAGES.some(([id])=>id===page)||!saveVisible())return;ui.page=page;if(!window.__DS_EMBEDDED__)history.replaceState(null,'','#'+page);render();window.scrollTo({top:0});$('#main').focus({preventScroll:true});}
function formData(form){return Object.fromEntries(new FormData(form));}
function saveForm(form){const f=formData(form),s=scene(),c=character();
 if(form.id==='character-form'){if(f.age!==undefined)f.age=Number(f.age);updateCharacter(f,c.name+' · details saved');}
 else if(form.id==='scene-form'){if(f.duration!==undefined){f.duration=Number(f.duration);f.contact=Math.min(s.contact,f.duration);f.effects={...s.effects,end:Math.min(s.effects.end,f.duration)};}if(f.fps!==undefined)f.fps=Number(f.fps);updateScene(f,s.name+' · '+ui.sceneTab+' saved');}
 else if(form.id==='effects-form')updateScene({effects:{...s.effects,...f,start:Number(f.start),end:Number(f.end),speed:Number(f.speed)}},s.name+' · time treatment');
 else if(form.id==='ambience-form')updateScene({ecology:f.ecology,ambience:s.ambience.map((a,i)=>({...a,enabled:!!f['enabled-'+i],level:Number(f['level-'+i])})),roomTone:!!f['enabled-0'],streetSound:!!f['enabled-1']},s.name+' · atmosphere');
 else if(form.id==='calibration-form')updateCharacter({calibrations:c.calibrations.map((r,i)=>i<c.profile/8?{height:f['height-'+i],pitch:f['pitch-'+i],distance:f['distance-'+i]}:r)},c.name+' · camera calibration');
 else if(form.id==='review-form')commit('review','Director’s review notes',n=>n.reviewNotes=f.reviewNotes);
 dirtyForms.delete(form.id);ui.dirty=dirtyForms.size>0;notify('Draft saved on this device.');
}
function bindForms(){for(const form of $$('main form')){form.addEventListener('input',()=>{dirtyForms.add(form.id);ui.dirty=true;$('#save-state').textContent='Unsaved form changes';});form.addEventListener('submit',e=>{e.preventDefault();dirtyForms.add(form.id);ui.dirty=true;if(saveVisible())render();});}
 $('#workspace')?.addEventListener('change',e=>cloud.workspace=e.target.value);
 $('#cast-add-select')?.addEventListener('change',e=>{if(e.target.value)run('cast-add',e.target.value);});
 $('#coverage-profile')?.addEventListener('change',e=>{const profile=Number(e.target.value);if(!saveVisible())return;try{updateCharacter({profile},character().name+' · coverage profile');render();}catch(e){notify(e.message,true);}});
 for(const input of $$('.ambience-row input[type=range]'))input.oninput=()=>input.nextElementSibling.textContent=input.value+'%';
}
function bindFilters(){for(const [id,attr]of [['catalog-search','character'],['review-search','review'],['connection-search','provider']])$('#'+id)?.addEventListener('input',e=>{for(const el of $$('[data-'+attr+']'))el.hidden=!el.dataset[attr].toLowerCase().includes(e.target.value.toLowerCase());});}
function bindStage(){const svg=$('#stage-svg');if(!svg)return;let drag=null;
 const position=e=>{const point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const q=point.matrixTransform(svg.getScreenCTM().inverse());return {x:Math.round(Math.max(0,Math.min(100,(q.x-70)/6.4))),y:Math.round(Math.max(0,Math.min(100,(q.y-65)/3.2)))};};
 svg.onpointerdown=e=>{const mark=e.target.closest('[data-cast]');if(!mark||!saveVisible())return;e.preventDefault();ui.castId=mark.dataset.cast;drag={id:mark.dataset.cast,start:position(e),element:mark};svg.setPointerCapture(e.pointerId);};
 svg.onpointermove=e=>{if(!drag)return;const pos=position(e);drag.pos=pos;drag.element.setAttribute('transform',`translate(${70+pos.x*6.4},${65+pos.y*3.2})`);};
 svg.onpointerup=e=>{if(!drag)return;try{if(drag.pos){const cast=structuredClone(scene().cast),i=cast.find(i=>i.id===drag.id);Object.assign(i,drag.pos);updateScene({cast},scene().name+' · cast blocking');}}catch(err){notify(err.message,true);}drag=null;render();};
 svg.onpointercancel=()=>{drag=null;render();};
 svg.onkeydown=e=>{const mark=e.target.closest('[data-cast]');if(!mark)return;const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!delta)return;e.preventDefault();const cast=structuredClone(scene().cast),i=cast.find(i=>i.id===mark.dataset.cast);i.x=Math.max(0,Math.min(100,i.x+delta[0]));i.y=Math.max(0,Math.min(100,i.y+delta[1]));try{updateScene({cast},scene().name+' · cast blocking');render();$(`[data-cast="${CSS.escape(i.id)}"]`)?.focus();}catch(err){notify(err.message,true);}};
}
function setPlayhead(t){playTime=t;const s=scene(),el=$('#playback');if(!el)return;const active=s.cues.filter(c=>c.start<=t&&c.start+c.duration>t).map(c=>c.label);el.textContent=active.length?active.join(' · '):'No cue at this moment';$('#timecode').textContent=t.toFixed(2).padStart(5,'0')+' / '+s.duration.toFixed(2);$('#scrubber').value=t;for(const cue of $$('.cue')){const c=s.cues.find(x=>x.id===cue.dataset.id);cue.classList.toggle('playing',c&&c.start<=t&&c.start+c.duration>t);}}
function bindScrubber(){$('#scrubber')?.addEventListener('input',e=>{stopPlayback();setPlayhead(Number(e.target.value));});}
function modal(title,content,{wide=false}={}){closeModal();modalReturn=document.activeElement;$('#modal').innerHTML=`<div class="dialog-head"><div><span class="eyebrow">Design Studio</span><h2>${title}</h2></div><button class="icon-btn" data-act="modal-close" aria-label="Close dialog">${icon('close',22)}</button></div><div class="dialog-body">${content}</div>`;$('#modal').classList.toggle('wide-dialog',wide);$('#modal').showModal();}
function closeModal(){if($('#modal').open){$('#modal').close();modalReturn?.focus?.();}}
function modalForm(title,body,submit,label='Save draft',extras=''){modal(title,`<form id="dialog-form">${body}<div class="dialog-actions">${extras}${btn('Cancel','modal-close')}${btn(label,null,{submit:true,primary:true,icon:'save'})}</div></form>`);$('#dialog-form').onsubmit=e=>{e.preventDefault();try{submit(formData(e.target));closeModal();render();notify('Draft saved.');}catch(err){notify(err.message,true);}};}
function historyDocument(h){return h.document?.schema===2?h.document:null;}
function diffRows(a,b,path='',out=[]){if(out.length>200)return out;if(JSON.stringify(a)===JSON.stringify(b))return out;if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)])){if(['history','savedAt','exportedAt'].includes(k))continue;diffRows(a[k],b[k],path?path+'.'+k:k,out);}}else out.push([path,a,b]);return out;}
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...(cloud.session?{Authorization:`Bearer ${cloud.session.access_token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||data.message||'Request failed.');return data;}
async function run(action,id){try{
 if(!['modal-close','command','guide','recover-export','recover-new'].includes(action)&&!$('#modal').open&&!saveVisible())return;
 const s=scene(),c=character();
 if(action==='modal-close'){closeModal();return;}
 if(action==='character-new')modalForm('Create a character',field('Character name','name','','text',{required:true})+field('Age','age',18,'number',{min:0,max:150,required:true})+field('Origin / upbringing','origin',''),f=>{const ch=makeCharacter({id:uid(),name:f.name,age:Number(f.age),origin:f.origin,representation:'',height:'',weight:'',hair:'',glasses:'',clothing:'',voice:'Not set',productUrl:'',revision:1});commit('character',ch.name+' · created',n=>n.characters.push(validateCharacter(ch)));ui.characterId=ch.id;ui.page='avatars';ui.avatarTab='identity';},'Create character');
 if(action==='character-select'){ui.characterId=id;render();}
 if(action==='identity-lock'){updateCharacter({identityLocked:!c.identityLocked},c.name+' · identity '+(c.identityLocked?'unlocked':'locked'));render();}
 if(action==='variant'){const variant=makeVariant(c);commit('character',variant.name+' · linked variant',n=>n.characters.push(variant));ui.characterId=variant.id;ui.page='avatars';ui.avatarTab='appearance';render();notify('16-view wardrobe variant created. Master identity retained.');}
 if(action==='avatar-voice'){ui.page='avatars';ui.avatarTab='voice';render();}
 if(action==='scene-new')modalForm('Start a new scene',field('Scene name','name','','text',{required:true})+field('Space','space','Community Room','select',{values:['Community Room','Open Plaza','Sound Stage','City Street','Ship Interior']}),f=>{const sc=newScene(c.id);sc.name=f.name;sc.space=f.space;sc.cast[0].pinnedRevision=c.revision;commit('scene',f.name+' · created',n=>{n.scenes.push(sc);n.activeSceneId=sc.id;});ui.page='scenes';},'Create scene');
 if(['scene-select','scene-open'].includes(action)){p.activeSceneId=id;if(action==='scene-open')ui.page='scenes';persist(p);ui.dirty=false;render();}
 if(action==='scene-duplicate'){const sc=structuredClone(s);sc.id=uid();sc.name=s.name+' · Copy';sc.revision=1;commit('scene',sc.name,n=>{n.scenes.push(sc);n.activeSceneId=sc.id;});render();}
 if(action==='cast-add'){const ch=p.characters.find(c=>c.id===id);if(!ch)throw Error('Character not found.');const inst={id:uid(),characterId:id,pinnedRevision:ch.revision,x:Math.min(90,35+s.cast.length*12),y:60,facing:0,role:'Supporting',stateIn:'',stateOut:''};updateScene({cast:[...s.cast,inst]},s.name+' · '+ch.name+' added');ui.castId=inst.id;render();notify(ch.name+' added to '+s.name+'.');}
 if(action==='cast-repin'){const cast=structuredClone(s.cast),i=cast.find(i=>i.id===id);i.pinnedRevision=p.characters.find(c=>c.id===i.characterId).revision;updateScene({cast},s.name+' · cast revision updated');render();}
 if(action==='cast-edit'){const i=s.cast.find(i=>i.id===id);modalForm('Direct this cast member',`<div class="form-grid">${field('Role','role',i.role)}${field('Facing (degrees)','facing',i.facing,'number',{min:0,max:359})}${field('Position X','x',i.x,'number',{min:0,max:100})}${field('Position Y','y',i.y,'number',{min:0,max:100})}${field('Incoming state','stateIn',i.stateIn,'textarea',{wide:true})}${field('Outgoing state','stateOut',i.stateOut,'textarea',{wide:true})}</div>`,f=>updateScene({cast:s.cast.map(x=>x.id===id?{...x,...f,x:Number(f.x),y:Number(f.y),facing:Number(f.facing)}:x)},s.name+' · cast direction'),'Save direction',btn('Remove from scene','cast-remove',{id}));}
 if(action==='cast-remove'){updateScene({cast:s.cast.filter(i=>i.id!==id)},s.name+' · cast member removed');closeModal();render();}
 if(['prop-new','prop-edit'].includes(action)){const pr=s.props.find(x=>x.id===id)||{id:uid(),name:'',x:65,y:50,notes:''};modalForm('Scene prop',field('Prop name','name',pr.name,'text',{required:true})+`<div class="form-grid">${field('Position X','x',pr.x,'number',{min:0,max:100})}${field('Position Y','y',pr.y,'number',{min:0,max:100})}</div>`+field('Contact / continuity notes','notes',pr.notes,'textarea'),f=>{const next={...pr,...f,x:Number(f.x),y:Number(f.y)};updateScene({props:action==='prop-new'?[...s.props,next]:s.props.map(x=>x.id===id?next:x)},s.name+' · prop saved');},'Save prop',action==='prop-edit'?btn('Remove prop','prop-remove',{id}):'');}
 if(action==='prop-remove'){updateScene({props:s.props.filter(i=>i.id!==id)},s.name+' · prop removed');closeModal();render();}
 if(['cue-new','cue-edit'].includes(action)){const cue=s.cues.find(x=>x.id===id)||{id:uid(),track:'Performance',label:'',start:0,duration:1,actorId:c.id,dependsOn:'',notes:''};modalForm('Compose a cue',`<div class="form-grid">${field('Cue / exact dialogue','label',cue.label,'text',{required:true,wide:true})}${field('Track','track',cue.track,'select',{values:TRACKS})}${field('Performer','actorId',cue.actorId,'select',{values:[['','None / world'],...p.characters.map(c=>[c.id,c.name])]})}${field('Start (seconds)','start',cue.start,'number',{min:0,max:s.duration,step:.1})}${field('Duration (seconds)','duration',cue.duration,'number',{min:.1,max:s.duration,step:.1})}${field('Starts after this cue finishes','dependsOn',cue.dependsOn,'select',{wide:true,values:[['','No prerequisite'],...s.cues.filter(x=>x.id!==cue.id).map(x=>[x.id,x.label])]})}${field('Perception, contact, voice, and motion notes','notes',cue.notes,'textarea',{wide:true})}</div>`,f=>{const next={...cue,...f,start:Number(f.start),duration:Number(f.duration)};updateScene({cues:action==='cue-new'?[...s.cues,next]:s.cues.map(x=>x.id===id?next:x)},s.name+' · cue saved');},'Save cue',action==='cue-edit'?btn('Remove cue','cue-remove',{id}):'');}
 if(action==='cue-remove'){if(s.cues.some(c=>c.dependsOn===id))throw Error('Another cue depends on this one. Change that prerequisite before removing it.');updateScene({cues:s.cues.filter(c=>c.id!==id)},s.name+' · cue removed');closeModal();render();}
 if(action==='motion-add'){const m=MOTIONS[Number(id)];updateScene({cues:[...s.cues,{id:uid(),track:'Performance',label:m.action,start:0,duration:Math.min(s.duration,m.duration),actorId:c.id,dependsOn:'',notes:m.notes}]},s.name+' · '+m.name);render();}
 if(action==='effect-mode'){updateScene({effects:{...s.effects,mode:id}},s.name+' · '+id);render();}
 if(action==='reference-edit'){const index=Number(id),ref=c.references.find(r=>r.cell===index);modalForm('Reference '+coverageCells(c)[index].label,field('HTTPS reference link','url',ref?.url||'','url')+field('Capture / source notes','note',ref?.note||'','textarea')+`<p class="micro">Only a link is recorded. No asset is uploaded, generated, or marked production-approved.</p>`,f=>{if(f.url&&!safeProductUrl(f.url))throw Error('Reference links must use HTTPS without credentials.');updateCharacter({references:[...c.references.filter(r=>r.cell!==index),...(f.url?[{cell:index,url:f.url,note:f.note}]:[])]},c.name+' · reference '+index);},'Save reference');}
 if(['listing-new','listing-edit'].includes(action)){const l=p.listings.find(l=>l.id===id)||{id:uid(),name:'',category:'Character',description:'',files:'',compatibility:'',license:'',status:'Private draft'};modalForm('Prepare a private listing',field('Package name','name',l.name,'text',{required:true})+field('Category','category',l.category,'select',{values:['Character','Wardrobe','Environment','Performance','Effect']})+field('Description','description',l.description,'textarea')+field('Exact deliverables and files','files',l.files,'textarea')+field('Tested compatibility / known limits','compatibility',l.compatibility,'textarea')+field('Proposed license scope','license',l.license,'textarea'),f=>commit('listing',f.name+' · private package',n=>{const next={...l,...f,status:'Private draft'};n.listings=action==='listing-new'?[...n.listings,next]:n.listings.map(x=>x.id===id?next:x);}), 'Save private draft');}
 if(['rights-new','rights-edit'].includes(action)){const r=p.rights.find(r=>r.id===id)||{id:uid(),asset:'',holder:'',scope:'',evidence:'',expires:'',notes:''};modalForm('Record source permissions',field('Asset / package','asset',r.asset,'text',{required:true})+field('Rights holder / source','holder',r.holder)+field('Permitted scope','scope',r.scope,'textarea')+field('Evidence link','evidence',r.evidence,'url')+field('Expiry date','expires',r.expires,'date')+field('Notes and limitations','notes',r.notes,'textarea'),f=>{if(f.evidence&&!safeProductUrl(f.evidence))throw Error('Evidence must be an HTTPS link.');commit('rights',f.asset+' · rights recorded',n=>{const next={...r,...f,status:'Recorded, not verified'};n.rights=action==='rights-new'?[...n.rights,next]:n.rights.map(x=>x.id===id?next:x);});},'Record permissions');}
 if(action==='connector-notes'){const co=connectors.find(x=>x.id===id);modalForm(co.name+' · setup notes',`<p>${esc(co.capability)}</p>${field('Requirements, account ownership, and test evidence','notes',p.connectorNotes[id]||'','textarea',{rows:7})}<p class="micro">Keep passwords and API keys out of these notes. A note does not connect an account.</p>`,f=>commit('connection',co.name+' · setup notes',n=>n.connectorNotes[id]=f.notes));}
 if(action==='tier-select'){commit('settings',id+' · planning tier',n=>n.preferences.tier=id);render();notify('Planning tier selected. No billing or feature restrictions changed.');}
 if(action==='checkpoint'){commit('project','Project checkpoint',()=>{});render();notify('Project checkpoint saved.');}
 if(action==='history-compare'){const h=p.history.find(h=>h.id===id),old=historyDocument(h);const current=old?snapshot(p):h.kind==='character'?p.characters.find(c=>c.id===h.document.id):scene();const rows=diffRows(h.document,current);modal('Compare saved draft to current',`<p>${esc(h.label||h.kind)} · ${time(h.at)}</p><div class="table-wrap"><table><thead><tr><th>Field</th><th>Saved</th><th>Current</th></tr></thead><tbody>${rows.slice(0,120).map(([k,a,b])=>`<tr><td>${esc(k)}</td><td>${esc(typeof a==='object'?JSON.stringify(a):a)}</td><td>${esc(typeof b==='object'?JSON.stringify(b):b)}</td></tr>`).join('')||'<tr><td colspan="3">No content differences.</td></tr>'}</tbody></table></div>`,{wide:true});}
 if(action==='history-restore'){const h=p.history.find(h=>h.id===id);modal('Restore as a new draft',`<p>Restore ${esc(h.label||h.kind)} from ${time(h.at)}? The current project will remain in the revision history.</p><div class="dialog-actions">${btn('Cancel','modal-close')}${btn('Restore draft','history-confirm',{id,primary:true})}</div>`);}
 if(action==='history-confirm'){const h=p.history.find(h=>h.id===id),old=historyDocument(h);commit('restore','Restored '+(h.label||h.kind),n=>{if(old){const restored=migrateProject(old);const history=n.history;Object.assign(n,restored);n.history=history;for(const ch of n.characters)ch.revision=Math.max(ch.revision,p.characters.find(c=>c.id===ch.id)?.revision||0)+1;}else if(h.kind==='character'){const idx=n.characters.findIndex(c=>c.id===h.document.id);if(idx<0)throw Error('Character is not in the current project.');n.characters[idx]=makeCharacter({...validateCharacter(h.document),revision:n.characters[idx].revision+1});}else if(h.kind==='scene'){n.scenes[n.scenes.findIndex(s=>s.id===n.activeSceneId)]=validateScene({...h.document,revision:scene().revision+1},n.characters);}else throw Error('Legacy checkpoint cannot be restored by this editor.');});ui.characterId=p.characters[0].id;closeModal();render();notify('Restored as a new draft. Review changed cast revisions.');}
 if(action==='undo'){if(!undoStack.length)return;const prev=undoStack.pop();const next=migrateProject({...prev,history:p.history});persist(next);p=next;render();notify('Last saved edit undone.');}
 if(action==='export')download('visionweaver-design-studio-'+VERSION+'.json',draftExport(p.characters,s,p));
 if(action==='review-export')download('design-studio-review.md',`# Design Studio draft review\n\n${reviewProject(p).map(i=>`- **${i.area}: ${i.title}** — ${i.detail}`).join('\n')}\n\n## Director notes\n${p.reviewNotes}\n\nNo production approval is granted.`, 'text/markdown');
 if(action==='brief')modal('Direction brief',`<p>Compiled from the active scene and its cast. Resolve review items before provider execution.</p><pre class="brief">${esc(compileBrief(p,s))}</pre><div class="dialog-actions">${btn('Copy text','brief-copy',{icon:'copy'})}${btn('Download brief','brief-download',{primary:true,icon:'export'})}</div>`,{wide:true});
 if(action==='brief-copy'){await navigator.clipboard.writeText(compileBrief(p,s));notify('Direction brief copied.');}
 if(action==='brief-download')download('design-studio-direction-brief.txt',compileBrief(p,s),'text/plain');
 if(action==='preview'){if(playFrame){stopPlayback();return;}const start=performance.now(),offset=playTime>=s.duration?0:playTime;const tick=()=>{const t=Math.min(s.duration,offset+(performance.now()-start)/1000);setPlayhead(t);if(t<s.duration)playFrame=requestAnimationFrame(tick);else playFrame=0;};tick();}
 if(action==='import'){$('#import-file').click();}
 if(action==='recover-export')download('design-studio-original-recovery.json',originalRaw||'{}');
 if(action==='recover-new'){download('design-studio-original-recovery.json',originalRaw||'{}');loadError='';p=newProject();persist(p);render();}
 if(action==='guide')modal('From a character to a connected scene',`<ol class="guide-list"><li><b>Define your cast.</b> Save identity, appearance, and voice direction in Avatars.</li><li><b>Map your references.</b> Link the 32-view master or a 16-view wardrobe variant, then record camera calibration.</li><li><b>Build the scene.</b> Place cast members, add props, and record the world and camera.</li><li><b>Direct the moment.</b> Add performance cues and prerequisites. Save atmosphere and time treatment.</li><li><b>Review and hand off.</b> Resolve changed revisions, preserve incoming and outgoing states, and export the brief.</li></ol><p class="micro">Changes save in this browser. Export to move devices. Cloud setup, generation, and commerce are separate integration steps.</p>`);
 if(action==='command'){modal('Quick find',`<label class="search-box">${icon('search')}<input id="command-search" autofocus placeholder="Find a page…" aria-label="Find a page"></label><div class="command-list">${PAGES.map(([pid,label])=>`<button class="collection-item" data-command-page="${pid}">${icon(pid)}<span>${label}</span>${icon('arrow',16)}</button>`).join('')}</div>`);$('#command-search').oninput=e=>$$('[data-command-page]').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(e.target.value.toLowerCase()));$('#command-search').focus();}
 if(action==='connections-refresh'){await configure();render();notify('Local application connection status refreshed.');}
 if(action==='signin'){if(!client)throw Error('Authentication is not configured.');const {error}=await client.auth.signInWithOAuth({provider:id,options:{redirectTo:location.origin+location.pathname}});if(error)throw error;}
 if(action==='signout'){await client.auth.signOut();cloud.session=null;cloud.workspaces=[];cloud.versions=[];cloud.workspace='';render();}
 if(action==='workspace-new')modalForm('Create a cloud workspace',field('Workspace name','name','','text',{required:true}),()=>{},'Create workspace');
 if(action==='workspace-new')$('#dialog-form').onsubmit=async e=>{e.preventDefault();try{const data=await api('/api/workspaces','POST',formData(e.target));cloud.workspace=data[0].id;cloud.workspaces=await api('/api/workspaces');closeModal();render();}catch(err){notify(err.message,true);}};
 if(action==='cloud-save'){if(!cloud.workspace)throw Error('Select a cloud workspace first.');const body={workspace_id:cloud.workspace,kind:'project',name:s.name,document:draftExport(p.characters,s,p)};if(new TextEncoder().encode(JSON.stringify(body)).length>64000)throw Error('This project exceeds the current 64 KB cloud draft limit. Export JSON to preserve the complete project.');await api('/api/versions','POST',body);notify('Private cloud draft saved.');}
 if(action==='cloud-load'){if(!cloud.workspace)throw Error('Select a cloud workspace first.');cloud.versions=await api('/api/versions?workspace='+encodeURIComponent(cloud.workspace));render();}
 if(action==='cloud-restore'){const v=cloud.versions.find(v=>v.id===id);stageImport(v.document);}
 }catch(e){notify(e.message||'The change could not be saved.',true);}}
function stageImport(raw){try{const next=importDraft(raw);modal('Import a project draft',`<p>${next.characters.length} characters · ${next.scenes.length} scenes. This replaces the active draft. The current project is saved as a recovery checkpoint.</p><div class="dialog-actions">${btn('Cancel','modal-close')}${btn('Import draft','import-confirm',{primary:true})}</div>`);$('[data-act="import-confirm"]').onclick=e=>{e.stopPropagation();try{const backup={id:uid(),kind:'project',label:'Before project import',at:new Date().toISOString(),document:snapshot(p)};next.history=[backup,...p.history].slice(0,30);persist(next);undoStack.push(snapshot(p));p=next;ui.characterId=p.characters[0].id;ui.page='studio';ui.dirty=false;closeModal();render();notify('Project draft imported.');}catch(err){notify(err.message,true);}};}catch(e){notify(e.message,true);}}
$('#import-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('Draft import limit is 2 MB.');stageImport(JSON.parse(await f.text()));}catch(err){notify(err.message,true);}e.target.value='';};
document.addEventListener('click',e=>{const command=e.target.closest('[data-command-page]');if(command){closeModal();navigate(command.dataset.commandPage);return;}const tab=e.target.closest('[data-avatar-tab],[data-scene-tab],[data-history-tab],[data-stage]');if(tab){if(!saveVisible())return;for(const [key,prop]of [['avatarTab','avatarTab'],['sceneTab','sceneTab'],['historyTab','historyTab'],['stage','stage']])if(tab.dataset[key])ui[prop]=tab.dataset[key];render();return;}const nav=e.target.closest('[data-page]');if(nav){navigate(nav.dataset.page);return;}const act=e.target.closest('[data-act]');if(act)run(act.dataset.act,act.dataset.id);});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();run('command');}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(!$('#modal').open){if(ui.dirty){if(saveVisible())render();}else run('checkpoint');}}});
window.addEventListener('beforeunload',e=>{if(ui.dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{const target=location.hash.slice(1);if(PAGES.some(([id])=>id===target))navigate(target);});
async function configure(){if(window.__DS_EMBEDDED__)return;try{cloud.config=await api('/api/config');connectors=await api('/api/connectors');cloud.apiReady=true;if(cloud.config.cloudConfigured&&!client){client=createClient(cloud.config.supabaseUrl,cloud.config.publishableKey,{auth:{flowType:'pkce',storage:sessionStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange((_event,session)=>{cloud.session=session;setTimeout(async()=>{try{cloud.workspaces=session?await api('/api/workspaces'):[];if(!ui.dirty&&!$('#modal').open)render();}catch(e){notify(e.message,true);}},0);});const {data}=await client.auth.getSession();cloud.session=data.session;if(cloud.session)cloud.workspaces=await api('/api/workspaces');}}catch{cloud.apiReady=false;}}
render();configure().then(()=>{if(!ui.dirty&&!$('#modal').open)render();});
