export const VERSION='0.1.02';
export const TITLE='VisionWeaver | Design Studio';
export const BOARDS=['Character Detail Specifications Board','360 View Board','A Cast Board'];
export const sampleCharacter={id:'chicago-character',name:'Chicago Character',representation:'African American',age:47,origin:'Chicago, IL',height:'5 ft 11 in',weight:'302 lb',hair:'Trimmed',glasses:'Yes',clothing:'Charcoal Sweat Suit',voice:'Not Set',productUrl:'https://www.amazon.com/dp/B0BGLDDZ9N?ref=ppx_pop_mob_ap_share',productStatus:'Unverified',status:'Draft',coverage:0,revision:1};
export function newScene(){return {id:crypto.randomUUID(),name:'Community Room',space:'Community Room',characterId:'chicago-character',camera:'Camera 1',x:50,y:62,light:true,roomTone:true,streetSound:false,action:'Reach',reaction:'Glass Tips',contact:2,duration:6,revision:1};}
export function safeProductUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export function validateCharacter(c){if(!c||typeof c!=='object')throw Error('Character details are required.');if(!c.name?.trim()||c.name.length>120)throw Error('Enter a name with 1 to 120 characters.');if(!Number.isInteger(Number(c.age))||Number(c.age)<0||Number(c.age)>150)throw Error('Enter a whole-number age from 0 to 150.');if(c.productUrl&&!safeProductUrl(c.productUrl))throw Error('Product links must use HTTPS without embedded credentials.');for(const k of ['name','representation','origin','height','weight','hair','glasses','clothing','voice','productUrl'])if(c[k]!=null&&(typeof c[k]!=='string'||c[k].length>2000))throw Error('Character fields must be text of at most 2000 characters.');return {...c,age:Number(c.age),revision:Number.isInteger(c.revision)&&c.revision>=0?c.revision:0,status:'Draft',coverage:0};}
export function validateScene(s,characters){if(!s?.name?.trim())throw Error('Enter a scene name.');if(!characters.some(c=>c.id===s.characterId))throw Error('Select an existing character.');if(!['x','y'].every(k=>Number.isFinite(s[k])&&s[k]>=0&&s[k]<=100))throw Error('Character position must be between 0 and 100.');if(!['Community Room','Open Plaza'].includes(s.space))throw Error('Choose a supported space.');if(!Number.isFinite(s.duration)||s.duration<1||s.duration>60||!Number.isFinite(s.contact)||s.contact<0||s.contact>s.duration)throw Error('Contact time must fall within a 1 to 60 second scene.');return s;}
export function draftExport(characters,scene){return {format:'visionweaver.design-draft',version:VERSION,exportedAt:new Date().toISOString(),status:'DRAFT_NOT_PRODUCTION',characters,scene,coverage:'Reference views have not been created.',productVerification:'Pending',license:'No commercial license is granted by this draft export.'};}
